model:
  base_learning_rate: 8.0e-7
  target: ldm.models.diffusion.MSDFont_ddpm_distri.MSDFont_train_stage2_rec_model_distri
  params:
    parameterization: "x0"
    linear_start: 0.00085
    linear_end: 0.0120
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    edit_t1: 200
    edit_t2: 800
    first_stage_key: "image"
    cond_stage_key: "char_img"
    image_size: 16
    channels: 4
    cond_stage_trainable: False
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    scale_factor: 0.18215
    use_ema: False 
    # ckpt_path: /home/fubin/StableDiffusion/checkpoints/v2-1_512-ema-pruned.ckpt
    ckpt_path: /home/fubin/StableDiffusion/logs/rec_stage_epoch=79.ckpt

    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        use_checkpoint: True
        use_fp16: False
        image_size: 16 # unused
        in_channels: 4
        out_channels: 4
        model_channels: 128
        attention_resolutions: [ 2, 1, 1 ] 
        num_res_blocks: 2
        channel_mult: [ 1, 1, 2, 2 ] 
        num_head_channels: 64 
        use_spatial_transformer: True
        use_linear_in_transformer: True
        transformer_depth: 1
        context_dim: 128
        legacy: False

    first_stage_config:
      target: ldm.models.autoencoder.AutoencoderKL
      params:
        # ckpt_path: /home/fubin/StableDiffusion/checkpoints/v2-1_512-ema-pruned.ckpt
        ckpt_path: /home/fubin/StableDiffusion/logs/rec_stage_epoch=79.ckpt
        embed_dim: 4
        monitor: val/rec_loss
        ddconfig:
          double_z: true
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 4
          - 4
          num_res_blocks: 2
          attn_resolutions: []
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity

    cond_stage_config: "__is_first_stage__" # we do not use this setting, leaving this for better extensive in the future

    style_stage_config:
      target: ldm.models.MSDFont_encoder.miniUNet_enc_128

    trans_model_config:
      config_path: "configs/MSDFont/MSDFont_Train_Stage1_trans_model_predx0_miniUnet.yaml"
      model_path: "/home/fubin/StableDiffusion/logs/trans_epoch=79.ckpt"

data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 64
    num_workers: 5
    wrap: false
    train:
      target: taming.data.MSDFont_data_ttf.FontTTFTrain
      params:
        size: 128
        data_dirs: "/home/fubin/FontData/chn/ttfs/train_font"
        train_chars: "/home/fubin/FontData/chn/train_chars.json"
        source_path: "/home/fubin/FontData/chn/source.ttf"


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        # batch_frequency: 200
        batch_frequency: 5000
        max_images: 8
        increase_log_steps: False

  trainer:
    benchmark: True
